name: Verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  verify:
    name: Verify Deps and Codegen
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off

    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Add GOPATH/bin to PATH
      shell: bash
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"

    - name: Install Dependencies
      run: |
        go get github.com/golang/dep/cmd/dep
        go get github.com/google/ko/cmd/ko
        go get github.com/google/licenseclassifier
        go get github.com/google/go-licenses
        go get knative.dev/test-infra/tools/dep-collector

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: ./src/github.com/${{ github.repository }}

    - name: Update Codegen
      shell: bash
      run: |
        pushd ./src/github.com/${{ github.repository }}
        ./hack/update-codegen.sh
        popd

    - name: Verify
      shell: bash
      run: |
        pushd ./src/github.com/${{ github.repository }}
        if [[ -z "$(git status --porcelain)" ]]; then
            echo "${{ github.repository }} up to date."
        else
            repoDiff=$(git diff-index --name-only HEAD --)
            echo "Found diffs in: $repoDiff"
            echo "${{ github.repository }} is out of date. Please run hack/update-codegen.sh"
            exit 1
        fi
        popd
