apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: myapp
version: 0.1.0-SNAPSHOT
